
export const API_ENDPOINTS = {
  AUTHORIZATION: {
    GET_ALL: '/authorization',
    CHECK: '/authorization/check',
    COUNT: '/authorization/count',
    CREATE: '/authorization/create',
    GET_BY_ID: '/authorization/{id}',
    DELETE: '/authorization/{id}',
    UPDATE: '/authorization/{id}',
    AVAILABLE_OPERATIONS: '/authorization/{id}/options',
  },
  EXTERNAL_TASK: {
    LIST: '/external-task',
    COUNT: '/external-task/count',
    FETCH_AND_LOCK: '/external-task/fetchAndLock',
    COMPLETE: '/external-task/{id}/complete',
    FAILURE: '/external-task/{id}/failure',
    BPMN_ERROR: '/external-task/{id}/bpmnError',
    DELETE: '/external-task/{id}',
    UNLOCK: '/external-task/{id}/unlock',
    EXTEND_LOCK: '/external-task/{id}/extendLock',
    RETRY: '/external-task/{id}/retry',
  },
  HISTORIC_EXTERNAL_TASK_LOG: {
    LIST: '/history/external-task-log',
    COUNT: '/history/external-task-log/count',
    GET_BY_ID: '/history/external-task-log/{id}',
    DELETE: '/history/external-task-log/{id}',
    CLEAR: '/history/external-task-log/clear',
  },
  HISTORIC_TASK_INSTANCE: {
    LIST: '/history/task-instance',
    COUNT: '/history/task-instance/count',
    GET_BY_ID: '/history/task-instance/{id}',
    DELETE: '/history/task-instance/{id}',
    BULK_DELETE: '/history/task-instance/delete',
  },
  TASK: {
    LIST: '/task',
    LIST_BY_TENANT: '/task?tenantIdIn={tenantId}',
    COUNT: '/task/count',
    CREATE: '/task/create',
    GET_BY_ID: '/task/{id}',
    UPDATE: '/task/{id}',
    DELETE: '/task/{id}',
    ASSIGN: '/task/{id}/assignee',
    CLAIM: '/task/{id}/claim',
    UNCLAIM: '/task/{id}/unclaim',
    DELEGATE: '/task/{id}/delegate',
    COMPLETE: '/task/{id}/complete',
    SET_DUEDATE: '/task/{id}/duedate',
  },
  TASK_FORM: {
    GET_FORM_KEY: '/task/{id}/form',
    GET_RENDERED_FORM: '/task/{id}/rendered-form',
    GET_DEPLOYED_FORM: '/task/{id}/deployed-form',
    GET_FORM_VARIABLES: '/task/{id}/form-variables',
    SUBMIT_FORM: '/task/{id}/submit-form',
    RESOLVE_TASK: '/task/{id}/resolve',
  },
  TASK_ATTACHMENT: {
    LIST: '/task/{id}/attachment',
    CREATE: '/task/{id}/attachment/create',
    GET_BY_ID: '/task/{id}/attachment/{attachmentId}',
    DELETE: '/task/{id}/attachment/{attachmentId}',
    GET_CONTENT: '/task/{id}/attachment/{attachmentId}/content',
  },
  TASK_COMMENT: {
    LIST: '/task/{id}/comment',
    CREATE: '/task/{id}/comment/create',
    GET_BY_ID: '/task/{id}/comment/{commentId}',
  },
  TASK_IDENTITY_LINK: {
    LIST: '/task/{id}/identity-links',
    CREATE: '/task/{id}/identity-links',
    DELETE: '/task/{id}/identity-links/delete',
  },
  TASK_LOCAL_VARIABLE: {
    LIST: '/task/{id}/localVariables',
    GET_BY_KEY: '/task/{id}/localVariables/{key}',
    CREATE: '/task/{id}/localVariables/{key}',
    UPDATE: '/task/{id}/localVariables/{key}',
    DELETE: '/task/{id}/localVariables/{key}',
    MODIFY: '/task/{id}/localVariables/modify',
  },
  TASK_VARIABLE: {
    LIST: '/task/{id}/variables',
    GET_BY_KEY: '/task/{id}/variables/{key}',
    CREATE: '/task/{id}/variables/{key}',
    UPDATE: '/task/{id}/variables/{key}',
    DELETE: '/task/{id}/variables/{key}',
    MODIFY: '/task/{id}/variables/modify',
  },
  PROCESS_DEFINITION: {
    LIST: '/process-definition',
    LIST_BY_TENANT: '/process-definition?tenantIdIn={tenantId}',
    GET_BY_ID: '/process-definition/{id}',
    GET_BY_KEY: '/process-definition/key/{key}',
    GET_BY_KEY_AND_TENANT: '/process-definition/key/{key}/tenant-id/{tenantId}',
    XML_BY_ID: '/process-definition/{id}/xml',
    XML_BY_KEY: '/process-definition/key/{key}/xml',
    XML_BY_KEY_AND_TENANT: '/process-definition/key/{key}/tenant-id/{tenantId}/xml',
    START_BY_ID: '/process-definition/{id}/start',
    START_BY_KEY: '/process-definition/key/{key}/start',
    START_BY_KEY_AND_TENANT: '/process-definition/key/{key}/tenant-id/{tenantId}/start',
    SUSPEND_BY_ID: '/process-definition/{id}/suspended',
    SUSPEND_BY_KEY: '/process-definition/key/{key}/suspended',
    SUSPEND_BY_KEY_AND_TENANT: '/process-definition/key/{key}/tenant-id/{tenantId}/suspended',
    ACTIVATE_BY_ID: '/process-definition/{id}/suspended',
    ACTIVATE_BY_KEY: '/process-definition/key/{key}/suspended',
    ACTIVATE_BY_KEY_AND_TENANT: '/process-definition/key/{key}/tenant-id/{tenantId}/suspended',
    DELETE_BY_ID: '/process-definition/{id}',
    DELETE_BY_KEY: '/process-definition/key/{key}',
    DELETE_BY_KEY_AND_TENANT: '/process-definition/key/{key}/tenant-id/{tenantId}',
  },
  PROCESS_INSTANCE: {
    LIST: '/process-instance',
    LIST_BY_TENANT: '/process-instance?tenantIdIn={tenantId}',
    GET_BY_ID: '/process-instance/{id}',
    ACTIVEINSTANCES_BY_ID: '/process-instance/{id}/activity-instances',
    VARIABLES_BY_ID: '/process-instance/{id}/variables',
  },
  HISTORIC_USER_OPERATION_LOG: {
    LIST: '/history/user-operation',
    COUNT: '/history/user-operation/count',
  },
  FILTER: {
    LIST: '/filter',
    CREATE: '/filter/create',
    GET_BY_ID: '/filter/{id}',
    UPDATE_BY_ID: '/filter/{id}',
    DELETE_BY_ID: '/filter/{id}',
    EXECUTE: '/filter/{id}/list',
    EXECUTE_COUNT: '/filter/{id}/count',
    EXECUTE_SINGLE: '/filter/{id}/singleResult',
    SORTING_OPTIONS: '/filter/sorting',
    GET_EXTENDED_INFO_BY_ID: '/filter/{id}/resource',
    UPDATE_EXTENDED_INFO: '/filter/{id}/resource/{resourceId}',
    DELETE_EXTENDED_INFO: '/filter/{id}/resource/{resourceId}',
    EXTENDED_INFO_COUNT: '/filter/{id}/resource/{resourceId}/count',
    EXTENDED_INFO_LIST: '/filter/{id}/resource/{resourceId}/list',
  },
  GROUP: {
    LIST: '/group',
    LIST_POST: '/group',
    COUNT: '/group/count',
    COUNT_POST: '/group/count',
    CREATE: '/group/create',
    GET_BY_ID: '/group/{id}',
    UPDATE: '/group/{id}',
    DELETE: '/group/{id}',
    GET_MEMBERS: '/group/{id}/members',
    ADD_MEMBER: '/group/{id}/members/{userId}',
    DELETE_MEMBER: '/group/{id}/members/{userId}',
    OPTIONS: '/group',
    MEMBERS_OPTIONS: '/group/{id}/members',
  },
  TENANT: {
    LIST: '/tenant',
    COUNT: '/tenant/count',
    CREATE: '/tenant/create',
    GET_BY_ID: '/tenant/{id}',
    UPDATE: '/tenant/{id}',
    DELETE: '/tenant/{id}',
    GET_GROUP_MEMBERS: '/tenant/{id}/group-members',
    ADD_GROUP_MEMBERS: '/tenant/{id}/group-members/{groupId}',
    DELETE_GROUP_MEMBERS: '/tenant/{id}/group-members/{groupId}',
    GROUP_MEMBERS_OPTIONS: '/tenant/{id}/group-members',
    MEMBERS_OPTIONS: '/tenant/{id}/user-members',
    UPDATE_MEMBERS: '/tenant/{id}/user-members/{userId}',
    DELETE_MEMBERS: '/tenant/{id}/user-members/{userId}'
  },
};
