
export const API_ENDPOINTS = {
  AUTHORIZATION: {
    GET_ALL: '/authorization',
    CHECK: '/authorization/check',
    COUNT: '/authorization/count',
    CREATE: '/authorization/create',
    GET_BY_ID: '/authorization/{id}',
    DELETE: '/authorization/{id}',
    UPDATE: '/authorization/{id}',
    AVAILABLE_OPERATIONS: '/authorization/{id}/options',
  },
  EXTERNAL_TASK: {
    LIST: '/external-task',
    COUNT: '/external-task/count',
    FETCH_AND_LOCK: '/external-task/fetchAndLock',
    COMPLETE: '/external-task/{id}/complete',
    FAILURE: '/external-task/{id}/failure',
    BPMN_ERROR: '/external-task/{id}/bpmnError',
    DELETE: '/external-task/{id}',
    UNLOCK: '/external-task/{id}/unlock',
    EXTEND_LOCK: '/external-task/{id}/extendLock',
    RETRY: '/external-task/{id}/retry',
  },
  HISTORIC_EXTERNAL_TASK_LOG: {
    LIST: '/history/external-task-log',
    COUNT: '/history/external-task-log/count',
    GET_BY_ID: '/history/external-task-log/{id}',
    DELETE: '/history/external-task-log/{id}',
    CLEAR: '/history/external-task-log/clear',
  },
  HISTORIC_TASK_INSTANCE: {
    LIST: '/history/task-instance',
    COUNT: '/history/task-instance/count',
    GET_BY_ID: '/history/task-instance/{id}',
    DELETE: '/history/task-instance/{id}',
    BULK_DELETE: '/history/task-instance/delete',
  },
  TASK: {
    LIST: '/task',
    COUNT: '/task/count',
    CREATE: '/task/create',
    GET_BY_ID: '/task/{id}',
    UPDATE: '/task/{id}',
    DELETE: '/task/{id}',
    ASSIGN: '/task/{id}/assignee',
    CLAIM: '/task/{id}/claim',
    UNCLAIM: '/task/{id}/unclaim',
    DELEGATE: '/task/{id}/delegate',
    COMPLETE: '/task/{id}/complete',
    SET_DUEDATE: '/task/{id}/duedate',
  },
  TASK_ATTACHMENT: {
    LIST: '/task/{id}/attachment',
    CREATE: '/task/{id}/attachment/create',
    GET_BY_ID: '/task/{id}/attachment/{attachmentId}',
    DELETE: '/task/{id}/attachment/{attachmentId}',
    GET_CONTENT: '/task/{id}/attachment/{attachmentId}/content',
  },
  TASK_COMMENT: {
    LIST: '/task/{id}/comment',
    CREATE: '/task/{id}/comment/create',
    GET_BY_ID: '/task/{id}/comment/{commentId}',
  },
  TASK_IDENTITY_LINK: {
    LIST: '/task/{id}/identity-links',
    CREATE: '/task/{id}/identity-links/create',
    DELETE: '/task/{id}/identity-links/{identityLinkId}',
    LIST_USERS: '/task/{id}/identity-links/users',
    LIST_GROUPS: '/task/{id}/identity-links/groups',
  },
  TASK_LOCAL_VARIABLE: {
    LIST: '/task/{id}/localVariables',
    GET_BY_KEY: '/task/{id}/localVariables/{key}',
    CREATE: '/task/{id}/localVariables/{key}',
    UPDATE: '/task/{id}/localVariables/{key}',
    DELETE: '/task/{id}/localVariables/{key}',
    MODIFY: '/task/{id}/localVariables/modify',
  },
  TASK_VARIABLE: {
    LIST: '/task/{id}/variables',
    GET_BY_KEY: '/task/{id}/variables/{key}',
    CREATE: '/task/{id}/variables/{key}',
    UPDATE: '/task/{id}/variables/{key}',
    DELETE: '/task/{id}/variables/{key}',
    MODIFY: '/task/{id}/variables/modify',
  },
};
